### ISSUE TITLE
Get user comments

### ISSUE THREAD

**Issue by Quantum-Codes** [Sid72020123/scratchconnect#10]
https://github.com/Sid72020123/scratchconnect/discussions/6#discussioncomment-1011901

Just to put this in To-Do list lol

**Comment by Sid72020123** [comment]
Should the title be get user and studio comments?

**Comment by Sid72020123** [comment]
I cannot find the API of the user and studio comments.

**Comment by Quantum-Codes** [comment]
Oops :P  I will try finding... I know its possible tho

**Comment by Sid72020123** [comment]
I found out how to get studio comments but not of user :(
Now I am going to update it on holidays because by exams are coming soon!

**Comment by Sid72020123** [comment]
I made a new update to get studio comments! No only user is remaining.

**Comment by Quantum-Codes** [comment]
Ok, my exams are gonna get over! The I will try finding the API. Can u give me the studio comment and project comment api links? That will help  a lot

If I get inbanned, then also it will help.  I will try to find

**Comment by Quantum-Codes** [comment]
I GOT SOMETHING!!!! https://scratch.mit.edu/site-api/comments/user/Ankit_Anmol/?page=1

**Comment by Quantum-Codes** [comment]
Is that good? Isk if u can do anything for that with python though

**Comment by Quantum-Codes** [comment]
I got something else...  it diesnt work for me but everyone says it does https://scratch.mit.edu/api/v1/user/griffpatch/?format=json

**Comment by Sid72020123** [comment]
> I GOT SOMETHING!!!! https://scratch.mit.edu/site-api/comments/user/Ankit_Anmol/?page=1

I know that API but I can't fetch the data and it will take some time which will make the library slow.

**Comment by Sid72020123** [comment]
> I got something else... it diesnt work for me but everyone says it does https://scratch.mit.edu/api/v1/user/griffpatch/?format=json
I will ty this.

**Comment by Sid72020123** [comment]
I is not working even if I gave the headers :(

**Comment by Quantum-Codes** [comment]
:(

**Comment by Sid72020123** [comment]
Do you want to make a Scratch Username bot using this library?
I haven't got any API to get user comments but you can see the comments in the Messages.

**Comment by Quantum-Codes** [comment]
What username bot?

**Comment by Sid72020123** [comment]
A bot that follows your action when you comment on it's profile. Such as 'follow me' to follow you.

**Comment by Sid72020123** [comment]
I haven't found any comments API yet. :(

**Comment by Quantum-Codes** [comment]
But I'm blocked on scratch.  I can't do that :(

**Comment by Quantum-Codes** [comment]
Can u give projects/studios API? should be related

**Comment by Sid72020123** [comment]
For project: https://api.scratch.mit.edu/users/Sid72020123/projects/1/comments/
For studio: https://api.scratch.mit.edu/studios/1/comments/
I checked they are not related to user comments.

**Comment by Quantum-Codes** [comment]
Oh

**Comment by Quantum-Codes** [comment]
I'm trying to make my own api... I am able to get "parent comments" in python but I need to also get the replies.. 
Also need to convert them to dictionary 
Also.... aghhh I only gave the first page data

**Comment by Quantum-Codes** [comment]
https://github.com/Quantum-Codes/Profile-comments-API  what u need in API? make issue there.

**Comment by Sid72020123** [comment]
I too was working on that! I have almost finished it but a little is remaining!

**Comment by Quantum-Codes** [comment]
@Sid72020123  gimme the link

**Comment by Sid72020123** [comment]
Fixed this issue! Thanks to @Quantum-Codes
