### ISSUE TITLE
Add support for TurboWarp cloud variables.

### ISSUE THREAD

**Issue by ajsya** [Sid72020123/scratchconnect#23]
Is possible; I've seen it done with Scratch2Py

**Comment by Quantum-Codes** [comment]
It is possible with websicket connection.
@Sid72020123 , we can't GET request :( 
https://clouddata.turbowarp.org/logs?projectid=612229554

**Comment by Quantum-Codes** [comment]
Ok, there's discussions for adding GET

**Comment by Sid72020123** [comment]
Yes. I am working on making that feature...

**Comment by Sid72020123** [comment]
The code was ready but in some Windows 10 machines the SSL certificate has been expired... So it may take some time to make this feature. Sorry.

**Comment by Sid72020123** [comment]
I finally found a solution to that certificate error! The working on this feature will be started soon...

**Comment by Sid72020123** [comment]
@ajsya I finally added that feature in ScratchConnect **but will be released soon** after some Cloud tests...
**But that would have less features than the original Scratch Project Cloud Connection** but it will include features like set variable, encode, decode, encode list, decode list. You can only read a variable's value and name which was recently updated as Turbowarp provides less data about those variables :(

**Comment by ajsya** [comment]
Ok, sounds good. :)
