### ISSUE TITLE
Cloud Variable IndexError: list index out of range

### ISSUE THREAD

**Issue by suvidhpawar** [Sid72020123/scratchconnect#24]
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    variable_value = variables.get_cloud_variable_value(variable_name='Name')[0]  # Get the variable value
IndexError: list index out of range

**Comment by Sid72020123** [comment]
Maybe that variable has no value... Try setting the cloud variable...

**Comment by Sid72020123** [comment]
Can you share the code so that I can figure out the problem?

**Comment by ajsya** [comment]
Usually when I've ran into this problem there just isn't any data for the cloud variable. Like he said, either try recreating the cloud variable or setting data to it (probably in Scratch).

**Comment by Sid72020123** [comment]
> Usually when I've ran into this problem there just isn't any data for the cloud variable. Like he said, either try recreating the cloud variable or setting data to it (probably in Scratch).

Yes

**Comment by Sid72020123** [comment]
Closing this issue...
