### ISSUE TITLE
Random crash when setting a cloud variable

### ISSUE THREAD

**Issue by idkhow2type** [Sid72020123/scratchconnect#29]
Occasionally, right after setting a cloud variable, everything crashes, without any errors. Can you look into it? Thanks!

**Comment by Sid72020123** [comment]
Can you send the error or the code here?
So that I can figure out the problem...

**Comment by Sid72020123** [comment]
Maybe you were spamming the Scratch Server and the server disconnected you...
Try using time.sleep()
Or use try/except statement to catch and handle the error when the Cloud creashes...

**Comment by Sid72020123** [comment]
@idkhow2type Is the issue still there?

**Comment by idkhow2type** [comment]
Sorry for taking a while to respond, here's the code for what I'm doing: https://gist.github.com/idkhow2type/fec1374aa7f8577f51f1ca74076c6d9f
For context, I'm making a Scratch project that can read its comments

**Comment by Sid72020123** [comment]
According to your code, the line no. 15 should be CLOUD.set_cloud_variable()

**Comment by Sid72020123** [comment]
As the issue has been solved [here](https://gist.github.com/idkhow2type/fec1374aa7f8577f51f1ca74076c6d9f), I will close this issue...
