### ISSUE TITLE
Get Messages Count not working.

### ISSUE THREAD

**Issue by Sid72020123** [Sid72020123/scratchconnect#3]
The get messages count is not working due to the API update of the Scratch Team.

**Comment by Quantum-Codes** [comment]
https://api.scratch.mit.edu/users/Ankit_Anmol/messages/count same api?

**Comment by Sid72020123** [comment]
Yes! But is now working when we call it in python or any other language :(

**Comment by Quantum-Codes** [comment]
> Yes! But is now working when we call it in python or any other language :(

Now or not?

**Comment by Quantum-Codes** [comment]
I know how to!

**Comment by Quantum-Codes** [comment]
#12

**Comment by Sid72020123** [comment]
Thank you for helping me!

**Comment by Quantum-Codes** [comment]
:)
