### ISSUE TITLE
Remove commenting, loving and faving functionality 

### ISSUE THREAD

**Issue by Chiroyce1** [Sid72020123/scratchconnect#35]
- It is already against Scratch's Terms of Use
- Most people don't use it, unlike the cloud variable features which are used a lot!
- Even if people do use it, it's probably for bad a reasons like spamming.

**Comment by Sid72020123** [comment]
Ok. I will think over it. React the above Chiroyce's comment with "thumbs up" or "thumbs down". Let's see how many people want that feature to be removed...

**Comment by webdev03** [comment]
Thumbs up is "remove it" thumbs down is "don't remove it" right?

**Comment by webdev03** [comment]
If you remove commenting, also remove love, favourite, follow,

**Comment by Chiroyce1** [comment]
> If you remove commenting, also remove love, favourite, follow,

Yes, we also don't need these. We need this library to be useful for people who want to make cool projects, and not for those who want to spam comments or use follow bots.

**Comment by Sid72020123** [comment]
Ok. I will remove those features soon. But it may take a long time as my school started and I'm in higher school now. I am busy now...
BTW what do you think of adding a limit. Such as which stops commenting twice on a user's profile and can't comment again until next hour? But he/she can comment on other user's profile only once per hour. I may do the same for loves, faves, and follows...

**Comment by Sid72020123** [comment]
> Thumbs up is "remove it" thumbs down is "don't remove it" right?

Yes.

**Comment by Sid72020123** [comment]
But people can still download earlier versions and make those spam bots...

**Comment by Chiroyce1** [comment]
> When you remove it keep the code in a separate repo so the code is still there in case of someone needing some code for that

It will still be there in the git history - a separate repo is not required.

**Comment by CubeyTheCube** [comment]
> > When you remove it keep the code in a separate repo so the code is still there in case of someone needing some code for that
> 
> It will still be there in the git history - a separate repo is **not** required.

What is the point of this in the first place, then? Anyone interested in making a bot would simply look in the history of the repository and see the code.

**Comment by Sid72020123** [comment]
No. I won't delete this...
Let me see if I can delete git history...

**Comment by webdev03** [comment]
Removing the git history would need everyone to re-clone right? What about the contributor list (depends on author emails)?

**Comment by Sid72020123** [comment]
Ok. So do you think that I should not delete this repo's history?

**Comment by Mbrick2** [comment]
If people are spamming they could just make there own requests using the request library. Its not rocket science (for comments at least. Cloud is very complex though)

**Comment by Sid72020123** [comment]
Yes. So should I remove this feature or no?

**Comment by Chiroyce1** [comment]
> If people are spamming they could just make there own requests using the request library. Its not rocket science (for comments at least. Cloud is very complex though)

This makes it a lot more easier. This will definitely reduce the amount of spam. But sadly we have a huge problem in front of us, most people use the older version and will not update.... so this is sort of pointless... **BUT** it will prevent any new spammers from rising..

**Comment by Sid72020123** [comment]
Yes. But if they are making bots, the code must be stored somewhere on the server. So during runtime, the library will be downloaded again to latest version, if the user has not given any version argument. I can delete all the previous versions on pypi. So, the previous versions will not get downloaded. But if the user has stored the library's code on the server and doesn't require installation, then that user might be able to make spam bots.

**Comment by Sid72020123** [comment]
Yes. I know. But we can request them to install the latest version...

**Comment by webdev03** [comment]
Some people don't like auto-updating open source software. Sometimes they believe it is not FLOSS software if it has auto updating mandatory.

**Comment by Chiroyce1** [comment]
> Some people don't like auto-updating open source software. Sometimes they believe it is not FLOSS software if it has auto updating mandatory.

We can't even enforce it - we have to give a reason for why they should update. And if we tell them the actual reason, they'd obviously not want to update (the spammers)

**Comment by webdev03** [comment]
The solution seems very empty, easily bypassed, also they'll all switch to scratchclient. I think all of the library makers should work together then. Also what if they are using DevTools Console?

**Comment by Chiroyce1** [comment]
Everyone, the point of this is not to completely stop spammers, but to discourage them from doing so. If we remove the functionality from this, then they'll have to make their own (either by referring the older commits or on their own), so they might feel like it's too much work and decide to stop spamming.

**Comment by Sid72020123** [comment]
Ok. Then I will remove those features. What about follow/unfollow?

**Comment by kccuber-scratch** [comment]
replit's poetry thing already updates modules. also remove the reporting functionality

**Comment by Chiroyce1** [comment]
> replit's poetry thing already updates modules. also remove the reporting functionality

thats a good idea - people using replit for spamming can not do so after the update, and reporting should definitely be removed as well.

**Comment by Sid72020123** [comment]
Oh. So reporting also causes spam? What about unfollowing?

**Comment by CubeyTheCube** [comment]
> Everyone, the point of this is not to completely stop spammers, but to discourage them from doing so. If we remove the functionality from this, then they'll have to make their own (either by referring the older commits or on their own), so they might feel like it's too much work and decide to stop spamming.

No spammer that would spam enough to become annoying would stop after being discouraged. All this does is curb functionality due to a few bad actors. Of course commenting using scripts is against the rules, but there are legitimate reasons that you could do so (it's not against the rules if you don't get caught) and what this does is discourage genuine creativity in favor of (possibly) mildly annoying some spammers. FWIW, I doubt any decent bot uses Python anyway because async in Python is weird, so it's pretty likely that this will have no effect on spammers. I don't think personal sentiment is a good tool to decide what gets removed from software.

**Comment by Chiroyce1** [comment]
After some thoughtful consideration, I feel like we should not remove this. The bots spamming aren't our problem, and the ST has shutdown a lot of them in the past 2-3 days. So technically instead of use trying to discourage the spammers, it's better if the ST bans them altogether.

**Comment by webdev03** [comment]
> FWIW, I doubt any decent bot uses Python anyway because async in Python is weird, so it's pretty likely that this will have no effect on spammers.

![image](https://user-images.githubusercontent.com/75148774/163317602-ecf82614-369c-4617-ac5e-4bc5980c41da.png)
When did the spamming start? For some reason at a similar time my package got a bunch of downloads... and there was complete silence earlier.

**Comment by Sid72020123** [comment]
Ok. So, should I keep those commenting and other functionalities? No need for removing them?

**Comment by webdev03** [comment]
It's not allowed to spam or bot @Chiroyce1

**Comment by webdev03** [comment]
> > It's not allowed to spam or bot @Chiroyce1
> 
> That would be a very weird restriction, and it'll still be able to spam others.

You said "it's better if the ST bans them altogether." but the ST already bans the spammers/botters?

**Comment by Sid72020123** [comment]
And ST deletes the spammed content. Right?

**Comment by Chiroyce1** [comment]
> And ST deletes the spammed content. Right?

They do, but only after a few hours. And not all of them. Spam comments from 5 days ago are still out there.

**Comment by Sid72020123** [comment]
Oh. The ST should have the way to delete all the spammed content.

**Comment by Sid72020123** [comment]
BTW @Chiroyce1 can also disallow commenting on his profile...

**Comment by Chiroyce1** [comment]
> BTW @Chiroyce1 can also disallow commenting on his profile...

That's not how the spam is going on. They're abusing the reply function to reply to ghost comments on other people's profiles, so I get a notification for a reply to a comment I never even made.

**Comment by Sid72020123** [comment]
Oh :(

**Comment by Quantum-Codes** [comment]
How about a new update where a reply automatically pings the parent commenter? This will eliminate ghost pings. Just idk what to do of people using older versions of the package.

_dumb idea: ask ST to require some other unnecessary piece of data which will break older versions of commenting_

**Comment by Sid72020123** [comment]
Oh. Let me think of that...
I think I will remove the whole commenting feature... Also, I can see that there is a tie in the votes...
Ok. Now, I need to remove the following (*Tell me if I can remove anything else or keep it*):

- commenting: user, studio, project
- report
- follow/unfollow
- love a project
- fave a project

Anything else?

**Comment by Sid72020123** [comment]
Oh. Now I can see that there are "6" votes for not removing that feature and "5" votes for removing it. I think not removing wins. But I will wait for today...

**Comment by Sid72020123** [comment]
What about adding a time limit in which a user can only post comments on the same profile only once per hour? But can comment on other's profile only once per hour.

**Comment by webdev03** [comment]
How will you make the time limit? People will find ways around it...

**Comment by Sid72020123** [comment]
Yes. In Python, you can't make an object private, though using "_". I think I should not remove those features. The Scratch Team should fix that ghost reply and add a way to stop spamming. Maybe they can add a time limit of 1 comment per 10 minutes or even more...

**Comment by webdev03** [comment]
If the ST limits to 1 comment per 10 minutes... Conversations would be ruined!

**Comment by Sid72020123** [comment]
Yes. Maybe they can add 1 comment per 10 minutes per 1 user. Which then will allow a user to post a comment on other user's profile per 10 minutes. Till then, he/she can comment on other user's profile.

**Comment by Chiroyce1** [comment]
> Yes. Maybe they can add 1 comment per 10 minutes per 1 user. Which then will allow a user to post a comment on other user's profile per 10 minutes. Till then, he/she can comment on other user's profile.

Still, that wouldn't be good. Then you cant have any real time conversations with just one person

**Comment by Sid72020123** [comment]
Yes :(
We should report the errors to Scratch Team for removing ghost ping and making a way to reduce or stop spam...

**Comment by Sid72020123** [comment]
I can see that the "don't remove" votes are more than "remove" votes. I think I will not remove these features.
The ghost reply should be fixed by the Scratch Team and they should have a way to stop spam.
I am going to close this issue on the next update...

**Comment by Sid72020123** [comment]
Closing this...

**Comment by Quantum-Codes** [comment]
To remove ghosting, the package can just make an additional request to the parent comment specified and automatically add the ping to the front. Just like how Scratch forces pings to be in front that we don't write.

Example: someone uses replying feature to reply to parent comment 12345. The package makes requestmto see the 12345 comment author and then adds it to the start.
("@" + parent comment author + " "  + what the User wanted to comment)

**Comment by Sid72020123** [comment]
I don't think that would work but I will try after some time...
