### ISSUE TITLE
Add a paragraph to hide passwords

### ISSUE THREAD

**Issue by Quantum-Codes** [Sid72020123/scratchconnect#38]
I have found atleast infinity people using the example login code as it is without hiding their password in a secret or environment variable...

Maybe we should try stopping that by suggesting to hide them in things like repl secrets or dotenv stuff

**Comment by Sid72020123** [comment]
Ok. I will add that in the Readme in the next update...

**Comment by Sid72020123** [comment]
I have updated the library and added a note above the login code. I will close this now...
