### ISSUE TITLE
Possibly remove the `ForbiddenLogin` exception as it causes a lot of confusion

### ISSUE THREAD

**Issue by Chiroyce1** [Sid72020123/scratchconnect#41]
(example: https://scratch.mit.edu/discuss/post/6336436/)

A lot of users think that there is an error in their code when they see an exception, and this happens a lot when `ForbiddenLogin` occurs, instead, how about a coloured print message that will calmly tell them how to fix it? Not the best idea, but I'm sure it'll reduce confusion and posts like the one above. We'll only add it for this one, since the others might be actual code related issues.

**Comment by Chiroyce1** [comment]
Do you want me make a PR? I can do it with plain ANSI sequences, and without requiring any extra dependencies.

**Comment by Chiroyce1** [comment]
@Sid72020123 Ok! It isn't very important so you can take your time, I just presented the idea.

**Comment by Sid72020123** [comment]
Ok. I added this in version 3.4. So I will close this now...

**Comment by Chiroyce1** [comment]
@CubeyTheCube I see that you've disliked my comment - do you mind telling why?

**Comment by Sid72020123** [comment]
Because I talked to them on other platforms and they said that they hate Scratch.
