### ISSUE TITLE
Can't change unauthorized project's cloud variables

### ISSUE THREAD

**Issue by oxendy** [Sid72020123/scratchconnect#42]
I used to change projects' cloud variables with the `set_cloud_variable` function even with projects that were not mine. But now, when I run the script, the scratch cloud variable won't change

Any ideas?

**Comment by oxendy** [comment]
I just found out that Scratch bans Replit's IP so prob it's Scratch's fault. Guess I've to log in using sessionID then

**Comment by Sid72020123** [comment]
Yes but loggin in with Session ID may not work now because Scratch made some
changes a few days ago :(
It now blocks a request sent from Replit! :(
Maybe, your program won't work.

**Comment by oxendy** [comment]
thats really really sucks. Any suggests for Replit alternatives?

**Comment by Sid72020123** [comment]
Sorry, I don't know any Replit alternatives. Many people are facing the same problem: https://scratch.mit.edu/discuss/topic/612435/

Also, this issue should be closed as it is not the library's error. It's the Scratch's API error which blocks the requests from Replit :(
