### ISSUE TITLE
API Change

### ISSUE THREAD

**Issue by WojtekCodesToday** [Sid72020123/scratchconnect#48]
Scratch API has changed, you can't now get unshared projects (or even view it on TW),  if it works, it can bemy fault

**Comment by Sid72020123** [comment]
Ok! Cool! So, I have to remove that features now...
Please wait for a few days until my exams get over.
I will plan to do that and delete some features. But releasing it (stable version), may take time. Maybe I will only be able to release next year in the month of March-April...

Connecting the cloud of unshared projects should work on Scratch but not on Turbowarp...
