### ISSUE TITLE
Why getting API needs account?

### ISSUE THREAD

**Issue by Quantum-Codes** [Sid72020123/scratchconnect#7]
I can simply go to https://api.scratch.mit.edu/users/Ankit_Anmol  to get data without login.

**Comment by Sid72020123** [comment]
Because sometimes to get messages an other stuff like setting cloud variables you need to have the essential data.

**Comment by Sid72020123** [comment]
Ok! Closing this issue.......

**Comment by Quantum-Codes** [comment]
That's fast!

**Comment by Sid72020123** [comment]
Thanks!
